EXPERIMENT:
    NAME: "kd,res50,mv2"
    PROJECT: "face_recognition distillation"
    LOG_DIR: "./log/"
DISTILLER:
    CLASS: "kd"
    TLoss: ""
    TEACHER: "ResNet50"
    STUDENT: "MobileNetV2"
    T_FC_PTH: "./model/data/res50_fc_weight.pt"
DATASET:
    NAME: "MS1MV3"
    DATA_DIR: "/data/tx/MS1MV3"
    BATCH_SIZE: 512
    NUM_WORKERS: 4
    NUM_CLASSES: 93431
    NUM_IMAGES: 5179510
SOLVER:
    TEACHER_PTH: "./model/data/res50_backbone.pth"
    EPOCHS: 48
    LR_SCHEDULER: "WarmupCosineAnnealingLR" # ['StepScaleLR', 'WarmupCosineAnnealingLR']
    MAX_LR: 0.1
    MIN_LR: 0.0000001
    WARMUP_EPOCH: 3
    WEIGHT_DECAY: 0.0005
    MOMENTUM: 0.9
    FP16: True
    TYPE: "SGD"
RESUME:
    IS_RESUME: False
    RESUME_EPOCH: 0
    RESUME_PATH: "./models/train_data/"
