EXPERIMENT:
    NAME: "KD+logit stand,res50,mv2"
    TAG: "KD+logit stand,res50,mv2"
    PROJECT: "face_recognition distillation"
    LOG_DIR: "./log/"
DISTILLER:
    TYPE: "KD+logit stand"
    CLASS: "fcd"
    TLoss: "v3"
    TEACHER: "ResNet50"
    STUDENT: "MobileNetV2"
DATASET:
    NAME: "MS1MV2"
    DATA_DIR: "/data/tx/MS1MV2"
    BATCH_SIZE: 512
    NUM_WORKERS: 4
    NUM_CLASSES: 85742
    NUM_IMAGES: 5822653
SOLVER:
    TEACHER_PTH: "./model/data/res50_backbone.pth"
    EPOCHS: 24
    LR_SCHEDULER: "WarmupPowerLR" # ['StepScaleLR', 'WarmupCosineAnnealingLR']
    MAX_LR: 0.1
    MIN_LR: 0.0000001
    WARMUP_EPOCH: 5
    WEIGHT_DECAY: 0.0005
    MOMENTUM: 0.9
    FP16: True
    TYPE: "SGD"
RESUME:
    IS_RESUME: False
    RESUME_EPOCH: 43
    RESUME_PATH: "log/KD+logit stand,res100,mv2_03-09_16-38"
