EXPERIMENT:
    NAME: "KD+logit stand,res50,mv2"
    TAG: "KD+logit stand,res50,mv2"
    PROJECT: "face_recognition distillation"
    LOG_DIR: "./log/"
DISTILLER:
    TYPE: "KD+logit stand"
    CLASS: "fcd"
    TLoss: "v1"
    TEACHER: "ResNet50"
    STUDENT: "MobileNetV2"
DATASET:
    NAME: "MS1MV3"
    DATA_DIR: "/data/tx/MS1MV3"
    BATCH_SIZE: 512
    NUM_WORKERS: 4
    NUM_CLASSES: 93431
    NUM_IMAGES: 5179510
SOLVER:
    TEACHER_PTH: "./model/data/res50_backbone.pth"
    EPOCHS: 48
    MAX_LR: 0.01
    LR_SCHEDULER: "StepScaleLR"
    LR_DECAY_STAGES: [15, 25, 34]
    LR_DECAY_RATE: 0.1
    WEIGHT_DECAY: 0.0005
    MOMENTUM: 0.9
    FP16: True
    TYPE: "SGD"
RESUME:
    IS_RESUME: False
    RESUME_EPOCH: 0
    RESUME_PATH: "./models/train_data/"
